# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parsers.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rparsers.proto\x12\x02pb\"!\n\x0cMangaRequest\x12\x11\n\tmangaName\x18\x01 \x01(\t\"\"\n\rMangaResponse\x12\x11\n\tmangaLink\x18\x01 \x01(\t29\n\x07Parsers\x12.\n\x05Parse\x12\x10.pb.MangaRequest\x1a\x11.pb.MangaResponse\"\x00\x42\nZ\x08thbot/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parsers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010thbot/pb'
  _globals['_MANGAREQUEST']._serialized_start=21
  _globals['_MANGAREQUEST']._serialized_end=54
  _globals['_MANGARESPONSE']._serialized_start=56
  _globals['_MANGARESPONSE']._serialized_end=90
  _globals['_PARSERS']._serialized_start=92
  _globals['_PARSERS']._serialized_end=149
# @@protoc_insertion_point(module_scope)
